#!/usr/bin/env node

import { program } from "commander";
import { wleAligner } from "./wle_aligner.js";

program
    .argument("<source-project-path>", "file path to the source Wonderland Engine project file")
    .argument("<target-project-path>", "file path to the target Wonderland Engine project file, that will be aligned to the source one")
    .option("-o, --output <path>", "where the aligned target project file will be stored\r (default: \"<target-project-dir>/target-<target-project-name>\")")
    .option("-r, --replace", "replace the original target project, ignoring the output option, if specified")
    .option("-u, --unsafe", "align the projects even if there is no bundle or it contains errors")
    .option("-b, --editor-bundle <path>", "path to the source/target project bundle, usually generated by building the project with the Wonderland Engine editor\r", "cache/js/_editor_bundle.cjs")
    .option("-e, --editor-bundle-extras <path>", "add extra definitions to the editor bundle via a JS script\r", "editor-bundle-extras.js")
    .action(wleAligner);

program.parseAsync();